module.exports = {
    config_defaults_nvenc: {
        "name": "DTV Uplink Server",
        "dtv_forward_host": "endpoint-dvb.ucomsite.my.id:15000",
        "dtv_forward_key": "",
        "dtv_geoblock": false,
        "dtv_protocol": "frps",
        "streams_path": "(pathname)/streams/",
        "dvr_path": "(pathname)/dvr/",
        "ffmpeg": "ffmpeg",
        //"watermark": "(pathname)/watermarks/lv-high-50-256-dark3.png",
        "watermark": "",
        "watermark_ignore_streams": [],
        "hls_settings": {
            "duration": 2,
            "list_size": 15,
            "unreferenced_segments": 10
        },
        "multiple_renditions": false,
        "nvenc_use_nvdec": true,
        "nvdec_use_scale": false,
        "use_cuvid": false,
        "nvdec_scale_exclude": [],
        "nvdec_sw_decode": [],
        "use_copyts": false,
        "async": "1",
        "vsync": "0",
        "disable_sync": false,
        "dtv_use_fork": true,
        "stall_do_not_restart_mux": [],
        "dtv_udp_out": {},
        "use_protocol": "udp",
        "dtv_tcp_use_copy": [],
        "dtv_ignore_map": [],
        "dtv_force_hd": [],
        "renditions_hd": [
            {
                "hwaccel": "nvenc",
                "width": 1280,
                "height": 720,
                "speed": 2,
                "profile": "high",
                "video_bitrate": 2000000,
                "bufsize": 2500000,
                "bf": 2,
                "interp_algo": 3,
                "audio_bitrate": 128000,
                "audio_profile": "low",
                "audio_codec": "aac"
            },
            {
                "hwaccel": "nvenc",
                "width": 960,
                "height": 540,
                "speed": 2,
                "profile": "high",
                "video_bitrate": 1000000,
                "bufsize": 1500000,
                "bf": 2,
                "interp_algo": 3,
                "audio_bitrate": 128000,
                "audio_profile": "low",
                "audio_codec": "aac"
            },
            {
                "hwaccel": "nvenc",
                "width": 640,
                "height": 360,
                "speed": 2,
                "profile": "main",
                "video_bitrate": 750000,
                "bufsize": 1250000,
                "bf": 2,
                "interp_algo": 3,
                "audio_bitrate": 96000,
                "audio_profile": "low",
                "audio_codec": "aac"
            },
            {
                "hwaccel": "nvenc",
                "width": 320,
                "height": 180,
                "speed": 2,
                "profile": "baseline",
                "video_bitrate": 375000,
                "bufsize": 875000,
                "bf": 2,
                "interp_algo": 3,
                "audio_bitrate": 64000,
                "audio_profile": "low",
                "audio_codec": "aac"
            }
        ],
        "renditions_sd": [
            {
                "hwaccel": "nvenc",
                "width": 960,
                "height": 540,
                "speed": 2,
                "profile": "high",
                "video_bitrate": 1000000,
                "bufsize": 1500000,
                "bf": 2,
                "interp_algo": 3,
                "audio_bitrate": 128000,
                "audio_profile": "low",
                "audio_codec": "aac"
            },
            {
                "hwaccel": "nvenc",
                "width": 640,
                "height": 360,
                "speed": 2,
                "profile": "main",
                "video_bitrate": 750000,
                "bufsize": 1250000,
                "bf": 2,
                "interp_algo": 3,
                "audio_bitrate": 96000,
                "audio_profile": "low",
                "audio_codec": "aac"
            },
            {
                "hwaccel": "nvenc",
                "width": 320,
                "height": 180,
                "speed": 2,
                "profile": "baseline",
                "video_bitrate": 375000,
                "bufsize": 875000,
                "bf": 2,
                "interp_algo": 3,
                "audio_bitrate": 64000,
                "audio_profile": "low",
                "audio_codec": "aac"
            }
        ],
        "rtmp_settings": {
            "port": 1935,
            "chunk_size": 60000,
            "gop_cache": true,
            "ping": 30,
            "ping_timeout": 60
        },
        "ll_mode": false,
        "lookahead": 0,
        "port": 6520,
        "play_port": 6521,
        "dtv_buffer_size": 2
    },
    config_defaults: {
        "name": "DTV Uplink Server",
        "dtv_forward_host": "endpoint-dvb.ucomsite.my.id:15000",
        "dtv_forward_key": "",
        "dtv_geoblock": false,
        "dtv_protocol": "frps",
        "streams_path": "(pathname)/streams/",
        "dvr_path": "(pathname)/dvr/",
        "ffmpeg": "ffmpeg",
        //"watermark": "(pathname)/watermarks/lv-high-50-256-dark3.png",
        "watermark": "",
        "watermark_ignore_streams": [],
        "hls_settings": {
            "duration": 2,
            "list_size": 15,
            "unreferenced_segments": 10
        },
        "multiple_renditions": false,
        "nvenc_use_nvdec": true,
        "nvdec_use_scale": false,
        "use_cuvid": false,
        "nvdec_scale_exclude": [],
        "nvdec_sw_decode": [],
        "use_copyts": false,
        "async": "1",
        "vsync": "0",
        "disable_sync": false,
        "dtv_use_fork": true,
        "stall_do_not_restart_mux": [],
        "dtv_udp_out": {},
        "use_protocol": "udp",
        "dtv_tcp_use_copy": [],
        "dtv_ignore_map": [],
        "dtv_force_hd": [],
        "renditions_hd": [
            {
                "hwaccel": "nvenc",
                "width": 1280,
                "height": 720,
                "speed": 2,
                "profile": "high",
                "video_bitrate": 2000000,
                "bufsize": 2500000,
                "bf": 2,
                "interp_algo": 3,
                "audio_bitrate": 128000,
                "audio_profile": "low",
                "audio_codec": "aac"
            },
            {
                "hwaccel": "nvenc",
                "width": 960,
                "height": 540,
                "speed": 2,
                "profile": "high",
                "video_bitrate": 1000000,
                "bufsize": 1500000,
                "bf": 2,
                "interp_algo": 3,
                "audio_bitrate": 128000,
                "audio_profile": "low",
                "audio_codec": "aac"
            },
            {
                "hwaccel": "nvenc",
                "width": 640,
                "height": 360,
                "speed": 2,
                "profile": "main",
                "video_bitrate": 750000,
                "bufsize": 1250000,
                "bf": 2,
                "interp_algo": 3,
                "audio_bitrate": 96000,
                "audio_profile": "low",
                "audio_codec": "aac"
            },
            {
                "hwaccel": "nvenc",
                "width": 320,
                "height": 180,
                "speed": 2,
                "profile": "baseline",
                "video_bitrate": 375000,
                "bufsize": 875000,
                "bf": 2,
                "interp_algo": 3,
                "audio_bitrate": 64000,
                "audio_profile": "low",
                "audio_codec": "aac"
            }
        ],
        "renditions_sd": [
            {
                "hwaccel": "vaapi",
                "width": 960,
                "height": 540,
                "speed": 2,
                "profile": "high",
                "video_bitrate": 1000000,
                "bufsize": 1500000,
                "bf": 2,
                "interp_algo": 2,
                "audio_bitrate": 128000,
                "audio_profile": "low",
                "audio_codec": "aac"
            },
            {
                "hwaccel": "vaapi",
                "width": 640,
                "height": 360,
                "speed": 2,
                "profile": "main",
                "video_bitrate": 750000,
                "bufsize": 1250000,
                "bf": 2,
                "interp_algo": 2,
                "audio_bitrate": 96000,
                "audio_profile": "low",
                "audio_codec": "aac"
            },
            {
                "hwaccel": "vaapi",
                "width": 320,
                "height": 180,
                "speed": 2,
                "profile": "578",
                "video_bitrate": 375000,
                "bufsize": 875000,
                "bf": 2,
                "interp_algo": 2,
                "audio_bitrate": 64000,
                "audio_profile": "low",
                "audio_codec": "aac"
            }
        ],
        "rtmp_settings": {
            "port": 1935,
            "chunk_size": 60000,
            "gop_cache": true,
            "ping": 30,
            "ping_timeout": 60
        },
        "ll_mode": false,
        "lookahead": 0,
        "port": 6520,
        "play_port": 6521,
        "dtv_buffer_size": 2
    }
}